# api/config/packages/api_platform.yaml
api_platform:
    metadata_backward_compatibility_layer: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
